### ISSUE TITLE
B+ Extra Pins Support

### ISSUE THREAD

**Issue by pmprog** [cypherkey/RaspberryPi.Net#26]
Is it possible to access the extra pins provided by the B+?

Thanks

**Comment by brunoamancio** [comment]
The new pins have to be mapped. See the class https://github.com/cypherkey/RaspberryPi.Net/blob/master/RaspberryPiDotNet/GPIOPins.cs

**Comment by pmprog** [comment]
Is that just a case of adding something like this?
```
V2_Pin_P1_29 = 5
```

**Comment by brunoamancio** [comment]
@pmprog , I don't know about the new version's hardware. I have not seen much about it, as I do not have it and can not work with it. I would do the implementation myself, but I can't make sure it works.

**Comment by pmprog** [comment]
I added these into my GPIOPins.cs; Seem to work okay

		V2Plus_Pin_P1_29 = 5,
		V2Plus_Pin_P1_31 = 6,
		V2Plus_Pin_P1_32 = 12,
		V2Plus_Pin_P1_33 = 13,
		V2Plus_Pin_P1_35 = 19,
		V2Plus_Pin_P1_36 = 16,
		V2Plus_Pin_P1_37 = 26,
		V2Plus_Pin_P1_38 = 20,
		V2Plus_Pin_P1_40 = 21,

**Comment by brunoamancio** [comment]
You could commit your changes to the repository, if you want.

**Comment by ivansager** [comment]
Added them too - all good so far.

**Comment by brunoamancio** [comment]
You could send a pull request with the changes. =)

**Comment by brunoamancio** [comment]
Added with https://github.com/cypherkey/RaspberryPi.Net/pull/28
