### ISSUE TITLE
Problem with Read GPIO

### ISSUE THREAD

**Issue by TewGer** [cypherkey/RaspberryPi.Net#31]
Hi there,

i have a Problem with reading a GPIO Value. I have written a litte source code in Visual Basic and C# too:

            GPIOFile gpio17 = new GPIOFile(GPIOPins.V2_GPIO_17);
            GPIOFile gpio24 = new GPIOFile(GPIOPins.V2_GPIO_24);
            while(true)
            {
                gpio17.Write(gpio24.read());

            }

My Compiler gives me the error, that the Method "Read" ist not presend in the .dll?

Does anyone have a solution for that?

edit: compiling the code direct on the pi2 is working, but on my pc with visual Basic not

Sorry for my bad english, it´s not my native language

**Comment by brunoamancio** [comment]
If you note the GPIOFile class has more constructors.

Take a look:

#region Constructor
        /// <summary>
        /// Access to the specified GPIO setup as an output port with an initial value of false (0)
        /// </summary>
        /// <param name="pin">The GPIO pin</param>
        public GPIOFile(GPIOPins pin)
            : this(pin,GPIODirection.Out,false)
        {
        }

        /// <summary>
        /// Access to the specified GPIO setup with the specified direction with an initial value of false (0)
        /// </summary>
        /// <param name="pin">The GPIO pin</param>
        /// <param name="direction">Direction</param>
        public GPIOFile(GPIOPins pin, GPIODirection direction)
            : this(pin, direction, false)
        {
        }

        /// <summary>
        /// Access to the specified GPIO setup with the specified direction with the specified initial value
        /// </summary>
        /// <param name="pin">The GPIO pin</param>
        /// <param name="direction">Direction</param>
        /// <param name="initialValue">Initial Value</param>
        public GPIOFile(GPIOPins pin, GPIODirection direction, bool initialValue)
            : base(pin, direction, initialValue)
        {
        }

        #endregion

So, if you want "gpio17" to receive a value, it must be an input. The overload GPIOFile(GPIOPins pin) sets the direction as output by default. So you can choose another one and specify the directions.

**Comment by TewGer** [comment]
thank your for your Response.

i know, i have tested it with different Options, but i always receive the error, that "read" ist not found. GPIOFile and MEM is not working.

**Comment by brunoamancio** [comment]
Which version is your RPi?

**Comment by TewGer** [comment]
Raspberry pi 2

**Comment by TewGer** [comment]
Update: i have build the .dll again and now it is working!!! I Think it was my mistake! 

Thank you very much for this great work brunoamacio!

**Comment by brunoamancio** [comment]
=) You're welcome.

**Comment by TewGer** [comment]
But i have another question:

GPIOFile ist working, but GPIOMem not, did you test it with the new Raspberry pi 2?

maybe i have didn´t unterstand a condition so it didn´t work?

**Comment by brunoamancio** [comment]
You can take a look at two other issues:

https://github.com/cypherkey/RaspberryPi.Net/issues/29
https://github.com/cypherkey/RaspberryPi.Net/issues/30
